language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-dsi-express' ]; then cd .. && eval "mv $currentfolder generator-dsi-express" && cd generator-dsi-express; fi

